# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hashtag Feminism
tagline:          We curate. They analyze. You discuss.
url:              http://xpmethod.plaintext.in/action-defense/
# baseurl:          http://xpmethod.plaintext.in/action-defense/
author:
  name:           Tara L. Conley
  url:            https://twitter.com/hashtagfeminism
  email:          hashtagfeminism@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/xpmethod/action-defense
